# Generated by Django 5.2.8 on 2025-11-26 03:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='Unknown Project Name', max_length=255)),
                ('no_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('completion_status', models.CharField(default='available', max_length=50)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('unit_type', models.CharField(max_length=100)),
                ('developer_name', models.CharField(max_length=255)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('area_sq_mtrs', models.IntegerField()),
                ('property_type', models.CharField(default='apartment', max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='US', max_length=5)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('features', models.TextField(default='[]')),
                ('facilities', models.TextField(default='[]')),
                ('project_description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_app.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_app.conversation')),
            ],
        ),
        migrations.CreateModel(
            name='VisitBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_app.lead')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_app.project')),
            ],
        ),
    ]
